"""Initial migration

Revision ID: 8b6c93477745
Revises: 
Create Date: 2025-01-16 18:26:36.229400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b6c93477745'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communication', schema=None) as batch_op:
        batch_op.drop_index('ix_communication_username')

    op.drop_table('communication')
    op.drop_table('attachment')
    op.drop_table('contact')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=15), nullable=True),
    sa.Column('email', sa.VARCHAR(length=128), nullable=True),
    sa.Column('organization', sa.VARCHAR(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('communication_id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('filetype', sa.VARCHAR(length=50), nullable=False),
    sa.Column('filepath', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['communication_id'], ['communication.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('communication',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=False),
    sa.Column('sent_message', sa.VARCHAR(length=140), nullable=True),
    sa.Column('received_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('communication', schema=None) as batch_op:
        batch_op.create_index('ix_communication_username', ['username'], unique=1)

    # ### end Alembic commands ###
